import type { Product, GalleryItem } from './database.types';

export const mockProducts: Product[] = [
  {
    id: '1',
    created_at: '2026-01-01T00:00:00Z',
    name: 'Chunky Knit Tote Bag',
    slug: 'chunky-knit-tote-bag',
    description:
      'A sturdy and stylish market tote hand-crocheted with natural cotton yarn. Perfect for groceries, beach days, or everyday use. Fully lined with a cotton canvas interior pocket.',
    price: 48,
    compare_at_price: 60,
    category: 'Bags',
    tags: ['tote', 'cotton', 'everyday'],
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80'],
    stock: 3,
    is_active: true,
    is_featured: true,
    yarn_weight: 'Bulky',
    hook_size: '6.0mm',
    dimensions: '35cm × 40cm',
    care_instructions: 'Hand wash cold, lay flat to dry',
  },
  {
    id: '2',
    created_at: '2026-01-15T00:00:00Z',
    name: 'Boho Sun Hat',
    slug: 'boho-sun-hat',
    description:
      'A breezy, open-weave sun hat crocheted from 100% raffia. Adjustable ribbon tie for a custom fit. Perfect for summer adventures.',
    price: 55,
    compare_at_price: null,
    category: 'Accessories',
    tags: ['hat', 'raffia', 'summer'],
    images: ['https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?w=600&q=80'],
    stock: 5,
    is_active: true,
    is_featured: true,
    yarn_weight: 'Fingering',
    hook_size: '3.5mm',
    dimensions: 'One size fits most',
    care_instructions: 'Spot clean only, reshape while damp',
  },
  {
    id: '3',
    created_at: '2026-02-01T00:00:00Z',
    name: 'Granny Square Cardigan',
    slug: 'granny-square-cardigan',
    description:
      'A vintage-inspired cardigan made of classic granny squares in a modern palette. Cozy, colourful, and completely one-of-a-kind.',
    price: 145,
    compare_at_price: null,
    category: 'Clothing',
    tags: ['cardigan', 'granny square', 'vintage'],
    images: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80'],
    stock: 1,
    is_active: true,
    is_featured: true,
    yarn_weight: 'Worsted',
    hook_size: '5.0mm',
    dimensions: 'S/M (can be custom sized)',
    care_instructions: 'Hand wash cold, reshape and dry flat',
  },
  {
    id: '4',
    created_at: '2026-02-10T00:00:00Z',
    name: 'Amigurumi Bunny',
    slug: 'amigurumi-bunny',
    description:
      'An adorable hand-stuffed crochet bunny, finished with safety eyes and embroidered details. Makes a wonderful gift for little ones.',
    price: 32,
    compare_at_price: null,
    category: 'Toys',
    tags: ['amigurumi', 'gift', 'kids'],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    stock: 8,
    is_active: true,
    is_featured: false,
    yarn_weight: 'DK',
    hook_size: '3.0mm',
    dimensions: '20cm tall',
    care_instructions: 'Surface wash only',
  },
  {
    id: '5',
    created_at: '2026-02-20T00:00:00Z',
    name: 'Sage Plant Hanger Set',
    slug: 'sage-plant-hanger-set',
    description:
      'A set of three macramé-style crochet plant hangers in sage green. Each is hand-knotted and includes a wooden dowel for hanging.',
    price: 38,
    compare_at_price: 45,
    category: 'Home',
    tags: ['plant hanger', 'home decor', 'set'],
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80'],
    stock: 4,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Worsted',
    hook_size: '5.0mm',
    dimensions: '50–80cm adjustable',
    care_instructions: 'Wipe with damp cloth',
  },
  {
    id: '6',
    created_at: '2026-03-01T00:00:00Z',
    name: 'Rainbow Wall Hanging',
    slug: 'rainbow-wall-hanging',
    description:
      'A cheerful woven rainbow wall hanging with tassels, made from merino wool remnants. No two are exactly alike.',
    price: 62,
    compare_at_price: null,
    category: 'Home',
    tags: ['wall art', 'rainbow', 'decor'],
    images: ['https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600&q=80'],
    stock: 0,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Bulky',
    hook_size: '7.0mm',
    dimensions: '40cm × 50cm',
    care_instructions: 'Do not wash, dust gently',
  },
];

export const mockGalleryItems: GalleryItem[] = [
  {
    id: 'g1',
    created_at: '2026-01-01T00:00:00Z',
    title: 'Chunky Knit Tote',
    description: 'Market-ready and made with love.',
    image_url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    alt_text: 'Chunky crocheted tote bag in natural cotton',
    product_id: '1',
    is_featured: true,
    display_order: 1,
  },
  {
    id: 'g2',
    created_at: '2026-01-15T00:00:00Z',
    title: 'Boho Summer Hat',
    description: 'Raffia sun hat, woven stitch by stitch.',
    image_url: 'https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?w=800&q=80',
    alt_text: 'Open-weave raffia sun hat',
    product_id: '2',
    is_featured: true,
    display_order: 2,
  },
  {
    id: 'g3',
    created_at: '2026-02-01T00:00:00Z',
    title: 'Granny Square Cardigan',
    description: 'Vintage vibes for the modern wardrobe.',
    image_url: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80',
    alt_text: 'Colourful granny square cardigan',
    product_id: '3',
    is_featured: true,
    display_order: 3,
  },
  {
    id: 'g4',
    created_at: '2026-02-10T00:00:00Z',
    title: 'Baby Bunny Friend',
    description: 'A little companion for little hands.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    alt_text: 'Amigurumi crochet bunny stuffed toy',
    product_id: '4',
    is_featured: false,
    display_order: 4,
  },
  {
    id: 'g5',
    created_at: '2026-02-20T00:00:00Z',
    title: 'Sage Plant Hangers',
    description: 'Bring life to your walls.',
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    alt_text: 'Crochet plant hangers in sage green',
    product_id: '5',
    is_featured: false,
    display_order: 5,
  },
  {
    id: 'g6',
    created_at: '2026-03-01T00:00:00Z',
    title: 'Rainbow Wall Art',
    description: 'A pop of colour for any room.',
    image_url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80',
    alt_text: 'Crochet rainbow wall hanging with tassels',
    product_id: '6',
    is_featured: true,
    display_order: 6,
  },
];
