import type { Product, GalleryItem } from './database.types';

/*
 * ZippyZack sells supplies, not finished goods — yarn on its own, yarn bundled
 * with the right hook and notions, complete project kits, tools, and patterns.
 * Categories here must stay in step with the filter list in src/pages/store.astro
 * and the category pills on the homepage: Yarn · Kits · Tools · Bundles · Patterns.
 *
 * Every image is a local file. Photographs are Pexels (free for commercial use,
 * no attribution required); the pattern charts ship with the design system.
 */
/*
 * category_id and updated_at are derived below rather than repeated on every
 * entry — these rows only stand in until Supabase is wired up.
 */
const mockProductSeeds: Omit<Product, 'category_id' | 'updated_at'>[] = [
  // ---------------------------------------------------------------- Yarn ---
  {
    id: '1',
    created_at: '2026-06-02T00:00:00Z',
    name: 'Merino Wool Yarn — Oatmeal',
    slug: 'merino-wool-yarn-oatmeal',
    description:
      'A soft, lofty merino in an undyed oatmeal that goes with everything. Spun in small batches, so each skein has a little character — expect gentle variation between dye lots. My go-to for jumpers, blankets and anything that sits against skin.',
    price: 14,
    compare_at_price: 18,
    category: 'Yarn',
    tags: ['merino', 'wool', 'aran', 'natural', 'undyed'],
    images: ['/assets/homepage-photos/pexels-arina-krasnikova-5709862.jpg'],
    stock: 24,
    is_active: true,
    is_featured: true,
    yarn_weight: 'Aran',
    hook_size: '5.0mm',
    dimensions: '100g · 180m per skein',
    care_instructions: 'Hand wash cold, lay flat to dry',
  },
  {
    id: '2',
    created_at: '2026-05-18T00:00:00Z',
    name: 'Pastel Cotton Yarn Set — 6 Balls',
    slug: 'pastel-cotton-yarn-set',
    description:
      'Six 50g balls of mercerised cotton in a soft pastel run — blush, butter, mint, sky, lilac and cream. Enough for a baby blanket or a whole run of granny squares, and the colours were picked to sit together without clashing.',
    price: 32,
    compare_at_price: null,
    category: 'Yarn',
    tags: ['cotton', 'pastel', 'set', 'dk', 'amigurumi'],
    images: ['/assets/homepage-photos/pexels-maria-sardar-15862201-6905162.jpg'],
    stock: 11,
    is_active: true,
    is_featured: false,
    yarn_weight: 'DK',
    hook_size: '4.0mm',
    dimensions: '6 × 50g · 125m per ball',
    care_instructions: 'Machine wash 30°C, do not tumble dry',
  },
  {
    id: '3',
    created_at: '2026-04-27T00:00:00Z',
    name: 'Undyed Cotton Yarn — 100g',
    slug: 'undyed-cotton-yarn',
    description:
      'Plain, honest cotton with no dye in it at all. Takes hand-dyeing beautifully if that is your thing, and holds a crisp stitch definition if it is not — this is the one I reach for when the pattern is the point.',
    price: 9,
    compare_at_price: null,
    category: 'Yarn',
    tags: ['cotton', 'undyed', 'natural', 'dyeable'],
    images: ['/assets/products/yarn-white-cotton.jpg'],
    stock: 40,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Sport',
    hook_size: '3.5mm',
    dimensions: '100g · 240m per ball',
    care_instructions: 'Machine wash 40°C, warm iron if needed',
  },
  {
    id: '4',
    created_at: '2026-04-09T00:00:00Z',
    name: 'Sage Macramé Cord — 3mm',
    slug: 'sage-macrame-cord',
    description:
      'A single-twist cotton cord in a muted sage, 3mm through. Heavy enough for plant hangers and wall pieces, soft enough that it will not fight your hands halfway through a row.',
    price: 16,
    compare_at_price: null,
    category: 'Yarn',
    tags: ['macrame', 'cord', 'cotton', 'sage', 'home'],
    images: ['/assets/products/yarn-rolls-green.jpg'],
    stock: 3,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Super Bulky',
    hook_size: '8.0mm',
    dimensions: '250g · 60m per roll',
    care_instructions: 'Spot clean only',
  },
  {
    id: '5',
    created_at: '2026-03-21T00:00:00Z',
    name: 'Alpaca Blend Trio — Earth',
    slug: 'alpaca-blend-trio-earth',
    description:
      'Three balls of alpaca-wool blend in bark, clay and sand. Warmer than it looks and lighter than it has any right to be — a scarf in this weighs almost nothing.',
    price: 27,
    compare_at_price: null,
    category: 'Yarn',
    tags: ['alpaca', 'blend', 'trio', 'winter', 'neutral'],
    images: ['/assets/products/yarn-rolls-natural.jpg'],
    stock: 7,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Worsted',
    hook_size: '4.5mm',
    dimensions: '3 × 100g · 150m per ball',
    care_instructions: 'Hand wash cold, dry flat away from heat',
  },
  {
    id: '6',
    created_at: '2026-03-05T00:00:00Z',
    name: 'Chunky T-Shirt Yarn — Stone',
    slug: 'chunky-tshirt-yarn-stone',
    description:
      'Recycled jersey cut and wound into a fat, stretchy yarn. Works up fast — a basket is an afternoon, a rug is a weekend. Go up a hook size or two from whatever you think you need.',
    price: 12,
    compare_at_price: null,
    category: 'Yarn',
    tags: ['t-shirt yarn', 'recycled', 'chunky', 'baskets', 'rugs'],
    images: ['/assets/products/yarn-grey-hook.jpg'],
    stock: 15,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Jumbo',
    hook_size: '10.0mm',
    dimensions: '400g · 100m per ball',
    care_instructions: 'Machine wash 30°C, reshape while damp',
  },

  // --------------------------------------------------------------- Tools ---
  {
    id: '7',
    created_at: '2026-06-11T00:00:00Z',
    name: 'Ergonomic Crochet Hook Set — 9 Sizes',
    slug: 'ergonomic-crochet-hook-set',
    description:
      'Nine aluminium hooks, 2.0mm through 6.0mm, each on a soft moulded grip with the size stamped where you can actually read it. If your hands ache after an hour, this is the fix — I switched to these years ago and never went back.',
    price: 24,
    compare_at_price: 30,
    category: 'Tools',
    tags: ['hooks', 'ergonomic', 'set', 'aluminium', 'beginner'],
    images: ['/assets/products/hook-set-colourful.jpg'],
    stock: 18,
    is_active: true,
    is_featured: true,
    yarn_weight: null,
    hook_size: '2.0 – 6.0mm',
    dimensions: '9 hooks · 14cm each',
    care_instructions: 'Wipe clean, store in the roll provided',
  },
  {
    id: '8',
    created_at: '2026-05-30T00:00:00Z',
    name: 'Soft-Grip Hook Set — 12 Pieces',
    slug: 'soft-grip-hook-set',
    description:
      'The wider range — twelve hooks from 0.9mm lace up to 8.0mm chunky, colour-coded by size so you can grab the right one without squinting. Comes in a zip case with room for scissors and markers.',
    price: 29,
    compare_at_price: null,
    category: 'Tools',
    tags: ['hooks', 'set', 'soft grip', 'lace', 'chunky'],
    images: ['/assets/products/hooks-row.jpg'],
    stock: 9,
    is_active: true,
    is_featured: false,
    yarn_weight: null,
    hook_size: '0.9 – 8.0mm',
    dimensions: '12 hooks · zip case included',
    care_instructions: 'Wipe clean, do not soak',
  },
  {
    id: '9',
    created_at: '2026-02-14T00:00:00Z',
    name: 'Aluminium Hook Set — 2.0 to 6.0mm',
    slug: 'aluminium-hook-set',
    description:
      'Plain aluminium, no grip, no fuss. Slick enough that the yarn slides rather than catches — if you crochet fast and tight, these will suit you better than anything moulded.',
    price: 15,
    compare_at_price: null,
    category: 'Tools',
    tags: ['hooks', 'aluminium', 'set', 'classic'],
    images: ['/assets/products/hook-set-arranged.jpg'],
    stock: 2,
    is_active: true,
    is_featured: false,
    yarn_weight: null,
    hook_size: '2.0 – 6.0mm',
    dimensions: '8 hooks · 15cm each',
    care_instructions: 'Wipe clean and dry',
  },
  {
    id: '10',
    created_at: '2026-01-28T00:00:00Z',
    name: 'Notions Starter Tin',
    slug: 'notions-starter-tin',
    description:
      'Everything that is not yarn and not a hook, in one tin — stitch markers, tapestry needles, a row counter, snips, a soft tape measure and a set of buttons. The things you only notice you are missing at row forty.',
    price: 21,
    compare_at_price: null,
    category: 'Tools',
    tags: ['notions', 'stitch markers', 'scissors', 'tape measure', 'accessories'],
    images: ['/assets/products/flatlay-yarn-hooks.jpg'],
    stock: 13,
    is_active: true,
    is_featured: false,
    yarn_weight: null,
    hook_size: null,
    dimensions: '14cm × 9cm tin · 28 pieces',
    care_instructions: 'Keep dry',
  },

  // ---------------------------------------------------------------- Kits ---
  {
    id: '11',
    created_at: '2026-06-20T00:00:00Z',
    name: 'Granny Square Starter Kit',
    slug: 'granny-square-starter-kit',
    description:
      'Yarn, hook and pattern for a run of twelve granny squares, plus enough left over to join them into a cushion cover. If you have never made a square before, start here — the pattern walks the first round stitch by stitch.',
    price: 38,
    compare_at_price: 46,
    category: 'Kits',
    tags: ['kit', 'granny square', 'beginner', 'cushion', 'yarn and tools'],
    images: ['/assets/products/granny-in-progress.jpg'],
    stock: 6,
    is_active: true,
    is_featured: true,
    yarn_weight: 'DK',
    hook_size: '4.0mm',
    dimensions: 'Makes 12 squares · 45cm × 45cm cushion',
    care_instructions: 'Finished piece: machine wash 30°C',
  },
  {
    id: '12',
    created_at: '2026-05-07T00:00:00Z',
    name: 'Amigurumi Beginner Kit',
    slug: 'amigurumi-beginner-kit',
    description:
      'One bunny, start to finish — cotton in three colours, a 3.0mm hook, safety eyes, stuffing, a needle and the printed pattern. Sized so a first attempt actually looks like a bunny.',
    price: 34,
    compare_at_price: null,
    category: 'Kits',
    tags: ['kit', 'amigurumi', 'beginner', 'toy', 'yarn and tools'],
    images: ['/assets/products/amigurumi-bunny-kit.jpg'],
    stock: 8,
    is_active: true,
    is_featured: false,
    yarn_weight: 'DK',
    hook_size: '3.0mm',
    dimensions: 'Finished bunny 18cm tall',
    care_instructions: 'Finished piece: surface wash only',
  },
  {
    id: '13',
    created_at: '2026-04-15T00:00:00Z',
    name: 'Learn to Crochet Kit',
    slug: 'learn-to-crochet-kit',
    description:
      'The absolute beginning — two balls of smooth cotton, a 4.5mm hook, scissors, markers and a set of practice cards that take you from a slip knot to a finished dishcloth. No experience needed, and nothing in the box you will outgrow.',
    price: 26,
    compare_at_price: null,
    category: 'Kits',
    tags: ['kit', 'beginner', 'learn', 'practice', 'yarn and tools'],
    images: ['/assets/products/kit-yarn-tools.jpg'],
    stock: 0,
    is_active: true,
    is_featured: false,
    yarn_weight: 'DK',
    hook_size: '4.5mm',
    dimensions: 'Makes 2 dishcloths · 25cm × 25cm',
    care_instructions: 'Finished piece: machine wash 40°C',
  },

  // ------------------------------------------------------------- Bundles ---
  {
    id: '14',
    created_at: '2026-06-25T00:00:00Z',
    name: 'Cosy Blanket Project Bundle',
    slug: 'cosy-blanket-project-bundle',
    description:
      'Ten balls of aran wool in a graded neutral run, an 8.0mm hook and the pattern for a throw big enough to actually cover someone. The biggest bundle I put together, and the one people come back for.',
    price: 96,
    compare_at_price: 118,
    category: 'Bundles',
    tags: ['bundle', 'blanket', 'throw', 'aran', 'project'],
    images: ['/assets/products/yarn-basket-earthy.jpg'],
    stock: 4,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Aran',
    hook_size: '8.0mm',
    dimensions: 'Finished throw 130cm × 170cm',
    care_instructions: 'Finished piece: hand wash cold, dry flat',
  },
  {
    id: '15',
    created_at: '2026-03-30T00:00:00Z',
    name: 'Scarf & Beanie Bundle',
    slug: 'scarf-and-beanie-bundle',
    description:
      'A matching pair in rust and dove grey — four balls, a 5.5mm hook and both patterns. Worked in the same stitch throughout, so once you have the scarf the beanie is the same thing in the round.',
    price: 44,
    compare_at_price: null,
    category: 'Bundles',
    tags: ['bundle', 'scarf', 'beanie', 'winter', 'project'],
    images: ['/assets/products/yarn-red-grey.jpg'],
    stock: 3,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Worsted',
    hook_size: '5.5mm',
    dimensions: 'Scarf 180cm × 20cm · beanie one size',
    care_instructions: 'Finished piece: hand wash cold, dry flat',
  },
  {
    id: '16',
    created_at: '2026-02-02T00:00:00Z',
    name: 'Market Bag Project Bundle',
    slug: 'market-bag-project-bundle',
    description:
      'Cotton in three colours, a 4.0mm hook and the mesh-stitch pattern for a bag that folds to nothing and carries far more than it should. Makes two, so one can be a gift.',
    price: 35,
    compare_at_price: null,
    category: 'Bundles',
    tags: ['bundle', 'bag', 'cotton', 'mesh', 'project'],
    images: ['/assets/products/yarn-basket-wicker.jpg'],
    stock: 10,
    is_active: true,
    is_featured: false,
    yarn_weight: 'DK',
    hook_size: '4.0mm',
    dimensions: 'Makes 2 bags · 35cm × 40cm each',
    care_instructions: 'Finished piece: machine wash 30°C',
  },

  // ------------------------------------------------------------ Patterns ---
  {
    id: '17',
    created_at: '2026-05-22T00:00:00Z',
    name: 'Granny Square Pattern Pack',
    slug: 'granny-square-pattern-pack',
    description:
      'Twelve granny square charts as a printable PDF — the classic, the solid, the flower centre and nine more, each drawn as a stitch diagram with a written round-by-round alongside it. Instant download, no shipping to wait for.',
    price: 8,
    compare_at_price: null,
    category: 'Patterns',
    tags: ['pattern', 'pdf', 'granny square', 'chart', 'download'],
    images: ['/assets/granny-patterns/granny-02.png'],
    stock: 999,
    is_active: true,
    is_featured: false,
    yarn_weight: 'DK',
    hook_size: '4.0mm',
    dimensions: '12 charts · 18-page PDF',
    care_instructions: 'Digital download — nothing ships',
  },
  {
    id: '18',
    created_at: '2026-01-12T00:00:00Z',
    name: 'Motif & Medallion Pattern Collection',
    slug: 'motif-and-medallion-pattern-collection',
    description:
      'Twenty round and hexagonal motifs, charted and written. Useful on their own as coasters and useful joined as almost anything — a blanket, a shawl, a table runner. Instant download.',
    price: 11,
    compare_at_price: null,
    category: 'Patterns',
    tags: ['pattern', 'pdf', 'motif', 'medallion', 'download'],
    images: ['/assets/granny-patterns/granny-04.png'],
    stock: 999,
    is_active: true,
    is_featured: false,
    yarn_weight: 'Sport',
    hook_size: '3.5mm',
    dimensions: '20 motifs · 26-page PDF',
    care_instructions: 'Digital download — nothing ships',
  },
];

export const mockProducts: Product[] = mockProductSeeds.map((p) => ({
  ...p,
  category_id: null,
  updated_at: p.created_at,
}));

/*
 * Finished pieces made from the kits above. product_id points at the product
 * the piece was made from, which is what the "Shop This Piece" link resolves.
 */
export const mockGalleryItems: GalleryItem[] = [
  {
    id: 'g1',
    created_at: '2026-06-22T00:00:00Z',
    title: 'Granny Square Throw',
    description: 'Ninety squares, one winter. Made from the starter kit.',
    image_url: '/assets/gallery/blanket-geometric.jpg',
    alt_text: 'Crocheted granny square blanket in mixed colours on grey fabric',
    product_id: '11',
    is_featured: true,
    display_order: 1,
  },
  {
    id: 'g2',
    created_at: '2026-06-04T00:00:00Z',
    title: 'The Bunny Family',
    description: 'One kit, then three more. It happens.',
    image_url: '/assets/gallery/amigurumi-bunnies.jpg',
    alt_text: 'Two crocheted bunny toys beside a pot of dried lavender',
    product_id: '12',
    is_featured: true,
    display_order: 2,
  },
  {
    id: 'g3',
    created_at: '2026-05-16T00:00:00Z',
    title: 'Ombré Baby Blanket',
    description: 'Pastel cotton, worked corner to corner.',
    image_url: '/assets/gallery/blanket-rolled.jpg',
    alt_text: 'Rolled crochet baby blanket graduating from peach to cream',
    product_id: '2',
    is_featured: true,
    display_order: 3,
  },
  {
    id: 'g4',
    created_at: '2026-04-30T00:00:00Z',
    title: 'Marigold the Cat',
    description: 'Off-pattern, entirely on purpose.',
    image_url: '/assets/gallery/amigurumi-cat.jpg',
    alt_text: 'Orange crocheted cat toy with green glasses',
    product_id: '12',
    is_featured: false,
    display_order: 4,
  },
  {
    id: 'g5',
    created_at: '2026-03-18T00:00:00Z',
    title: 'Chunky Stripe Throw',
    description: 'Two weekends in t-shirt yarn — worth every metre.',
    image_url: '/assets/gallery/blanket-stool.jpg',
    alt_text: 'Chunky crochet blanket in lilac and cream stripes folded over a stool',
    product_id: '14',
    is_featured: false,
    display_order: 5,
  },
  {
    id: 'g6',
    created_at: '2026-02-25T00:00:00Z',
    title: 'Shell Stitch, In Progress',
    description: 'Merino oatmeal on a 5.0mm hook — halfway there.',
    image_url: '/assets/gallery/project-wool-hooks.jpg',
    alt_text: 'Cream shell-stitch crochet piece in progress with a wooden hook',
    product_id: '1',
    is_featured: true,
    display_order: 6,
  },
];
